//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchDataServiceNS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataData", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataData : object
    {
        
        private System.Nullable<decimal> AssessedImprovementValueField;
        
        private System.Nullable<decimal> AssessedLandValueField;
        
        private SearchDataServiceNS.ReceiveSearchDataChainOfTitle[] ChainOfTitleField;
        
        private System.Nullable<System.DateTime> CommitmentEffectiveDateField;
        
        private System.Nullable<int> CommitmentInterestIDField;
        
        private SearchDataServiceNS.ReceiveSearchDataEasement[] EasementsField;
        
        private string FileNumberField;
        
        private string LeaseholdField;
        
        private string LegalField;
        
        private SearchDataServiceNS.ReceiveSearchDataLien[] LiensField;
        
        private string ParcelIDField;
        
        private string ProposedInsuredField;
        
        private SearchDataServiceNS.ReceiveSearchDataRequirement[] RequirementsField;
        
        private SearchDataServiceNS.ReceiveSearchDataRestriction[] RestrictionsField;
        
        private int ServiceVersionField;
        
        private SearchDataServiceNS.ReceiveSearchDataTax[] TaxesField;
        
        private string VestingField;
        
        private System.Nullable<int> YearAcquiredField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AssessedImprovementValue
        {
            get
            {
                return this.AssessedImprovementValueField;
            }
            set
            {
                this.AssessedImprovementValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AssessedLandValue
        {
            get
            {
                return this.AssessedLandValueField;
            }
            set
            {
                this.AssessedLandValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataChainOfTitle[] ChainOfTitle
        {
            get
            {
                return this.ChainOfTitleField;
            }
            set
            {
                this.ChainOfTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CommitmentEffectiveDate
        {
            get
            {
                return this.CommitmentEffectiveDateField;
            }
            set
            {
                this.CommitmentEffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CommitmentInterestID
        {
            get
            {
                return this.CommitmentInterestIDField;
            }
            set
            {
                this.CommitmentInterestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataEasement[] Easements
        {
            get
            {
                return this.EasementsField;
            }
            set
            {
                this.EasementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FileNumber
        {
            get
            {
                return this.FileNumberField;
            }
            set
            {
                this.FileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Leasehold
        {
            get
            {
                return this.LeaseholdField;
            }
            set
            {
                this.LeaseholdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Legal
        {
            get
            {
                return this.LegalField;
            }
            set
            {
                this.LegalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataLien[] Liens
        {
            get
            {
                return this.LiensField;
            }
            set
            {
                this.LiensField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelID
        {
            get
            {
                return this.ParcelIDField;
            }
            set
            {
                this.ParcelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProposedInsured
        {
            get
            {
                return this.ProposedInsuredField;
            }
            set
            {
                this.ProposedInsuredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataRequirement[] Requirements
        {
            get
            {
                return this.RequirementsField;
            }
            set
            {
                this.RequirementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataRestriction[] Restrictions
        {
            get
            {
                return this.RestrictionsField;
            }
            set
            {
                this.RestrictionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceVersion
        {
            get
            {
                return this.ServiceVersionField;
            }
            set
            {
                this.ServiceVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataTax[] Taxes
        {
            get
            {
                return this.TaxesField;
            }
            set
            {
                this.TaxesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vesting
        {
            get
            {
                return this.VestingField;
            }
            set
            {
                this.VestingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YearAcquired
        {
            get
            {
                return this.YearAcquiredField;
            }
            set
            {
                this.YearAcquiredField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataChainOfTitle", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataChainOfTitle : object
    {
        
        private SearchDataServiceNS.ReceiveSearchDataBookPage[] BookPagesField;
        
        private SearchDataServiceNS.BookPageDataRow[] ChainOfTitleBookPagesField;
        
        private System.Nullable<int> ChainOfTitleIDField;
        
        private System.Nullable<decimal> ConsiderationField;
        
        private System.Nullable<System.DateTime> DatedField;
        
        private string DeedBookVolumePageField;
        
        private string DeedTypeField;
        
        private string GranteesField;
        
        private string GrantorsField;
        
        private string InstrumentField;
        
        private string NotesField;
        
        private System.Nullable<System.DateTime> RecordedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataBookPage[] BookPages
        {
            get
            {
                return this.BookPagesField;
            }
            set
            {
                this.BookPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.BookPageDataRow[] ChainOfTitleBookPages
        {
            get
            {
                return this.ChainOfTitleBookPagesField;
            }
            set
            {
                this.ChainOfTitleBookPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ChainOfTitleID
        {
            get
            {
                return this.ChainOfTitleIDField;
            }
            set
            {
                this.ChainOfTitleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Consideration
        {
            get
            {
                return this.ConsiderationField;
            }
            set
            {
                this.ConsiderationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dated
        {
            get
            {
                return this.DatedField;
            }
            set
            {
                this.DatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeedBookVolumePage
        {
            get
            {
                return this.DeedBookVolumePageField;
            }
            set
            {
                this.DeedBookVolumePageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeedType
        {
            get
            {
                return this.DeedTypeField;
            }
            set
            {
                this.DeedTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grantees
        {
            get
            {
                return this.GranteesField;
            }
            set
            {
                this.GranteesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grantors
        {
            get
            {
                return this.GrantorsField;
            }
            set
            {
                this.GrantorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instrument
        {
            get
            {
                return this.InstrumentField;
            }
            set
            {
                this.InstrumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Recorded
        {
            get
            {
                return this.RecordedField;
            }
            set
            {
                this.RecordedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataEasement", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataEasement : SearchDataServiceNS.ReceiveSearchDataEasementRestrictionBase
    {
        
        private SearchDataServiceNS.BookPageDataRow[] EasementBookPagesField;
        
        private System.Nullable<int> EasementIDField;
        
        private System.Nullable<int> EasementTypeIDField;
        
        private string EasementTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.BookPageDataRow[] EasementBookPages
        {
            get
            {
                return this.EasementBookPagesField;
            }
            set
            {
                this.EasementBookPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EasementID
        {
            get
            {
                return this.EasementIDField;
            }
            set
            {
                this.EasementIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EasementTypeID
        {
            get
            {
                return this.EasementTypeIDField;
            }
            set
            {
                this.EasementTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EasementTypeName
        {
            get
            {
                return this.EasementTypeNameField;
            }
            set
            {
                this.EasementTypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataLien", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataLien : SearchDataServiceNS.ReceiveSearchDataLienRequirementBase
    {
        
        private SearchDataServiceNS.BookPageDataRow[] LienBookPagesField;
        
        private System.Nullable<int> LienIDField;
        
        private System.Nullable<int> LienTypeIDField;
        
        private string LienTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.BookPageDataRow[] LienBookPages
        {
            get
            {
                return this.LienBookPagesField;
            }
            set
            {
                this.LienBookPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LienID
        {
            get
            {
                return this.LienIDField;
            }
            set
            {
                this.LienIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LienTypeID
        {
            get
            {
                return this.LienTypeIDField;
            }
            set
            {
                this.LienTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LienTypeName
        {
            get
            {
                return this.LienTypeNameField;
            }
            set
            {
                this.LienTypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataRequirement", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataRequirement : SearchDataServiceNS.ReceiveSearchDataLienRequirementBase
    {
        
        private SearchDataServiceNS.BookPageDataRow[] LienBookPagesField;
        
        private System.Nullable<int> RequirementIDField;
        
        private System.Nullable<int> RequirementTypeIDField;
        
        private string RequirementTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.BookPageDataRow[] LienBookPages
        {
            get
            {
                return this.LienBookPagesField;
            }
            set
            {
                this.LienBookPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RequirementID
        {
            get
            {
                return this.RequirementIDField;
            }
            set
            {
                this.RequirementIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RequirementTypeID
        {
            get
            {
                return this.RequirementTypeIDField;
            }
            set
            {
                this.RequirementTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequirementTypeName
        {
            get
            {
                return this.RequirementTypeNameField;
            }
            set
            {
                this.RequirementTypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataRestriction", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataRestriction : SearchDataServiceNS.ReceiveSearchDataEasementRestrictionBase
    {
        
        private SearchDataServiceNS.BookPageDataRow[] EasementBookPagesField;
        
        private System.Nullable<int> RestrictionIDField;
        
        private System.Nullable<int> RestrictionTypeIDField;
        
        private string RestrictionTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.BookPageDataRow[] EasementBookPages
        {
            get
            {
                return this.EasementBookPagesField;
            }
            set
            {
                this.EasementBookPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RestrictionID
        {
            get
            {
                return this.RestrictionIDField;
            }
            set
            {
                this.RestrictionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RestrictionTypeID
        {
            get
            {
                return this.RestrictionTypeIDField;
            }
            set
            {
                this.RestrictionTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RestrictionTypeName
        {
            get
            {
                return this.RestrictionTypeNameField;
            }
            set
            {
                this.RestrictionTypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataTax", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataTax : object
    {
        
        private System.Nullable<bool> EstimatedField;
        
        private System.Nullable<decimal> ExemptionAdditionalField;
        
        private System.Nullable<decimal> ExemptionHomeownersField;
        
        private System.Nullable<decimal> ExemptionHomesteadSupplementalField;
        
        private System.Nullable<decimal> ExemptionMortgageField;
        
        private System.Nullable<bool> FirstDelinquentField;
        
        private System.Nullable<System.DateTime> FirstDelinquentDateField;
        
        private System.Nullable<System.DateTime> FirstDiscountDateField;
        
        private System.Nullable<bool> FirstDueField;
        
        private System.Nullable<System.DateTime> FirstDueDateField;
        
        private System.Nullable<bool> FirstEstimatedField;
        
        private System.Nullable<System.DateTime> FirstGoodThroughDateField;
        
        private System.Nullable<decimal> FirstInstallmentField;
        
        private System.Nullable<bool> FirstPaidField;
        
        private System.Nullable<System.DateTime> FirstPaidDateField;
        
        private System.Nullable<bool> FirstPartiallyPaidField;
        
        private System.Nullable<decimal> FirstPartiallyPaidAmountField;
        
        private System.Nullable<System.DateTime> FirstTaxesOutDateField;
        
        private System.Nullable<bool> FourthDelinquentField;
        
        private System.Nullable<System.DateTime> FourthDelinquentDateField;
        
        private System.Nullable<System.DateTime> FourthDiscountDateField;
        
        private System.Nullable<bool> FourthDueField;
        
        private System.Nullable<System.DateTime> FourthDueDateField;
        
        private System.Nullable<bool> FourthEstimatedField;
        
        private System.Nullable<System.DateTime> FourthGoodThroughDateField;
        
        private System.Nullable<decimal> FourthInstallmentField;
        
        private System.Nullable<bool> FourthPaidField;
        
        private System.Nullable<System.DateTime> FourthPaidDateField;
        
        private System.Nullable<bool> FourthPartiallyPaidField;
        
        private System.Nullable<decimal> FourthPartiallyPaidAmountField;
        
        private System.Nullable<System.DateTime> FourthTaxesOutDateField;
        
        private System.Nullable<decimal> ImprovementsField;
        
        private System.Nullable<decimal> LandField;
        
        private string NotesField;
        
        private System.Nullable<decimal> OtherField;
        
        private System.Nullable<int> PaymentFrequencyTypeIDField;
        
        private string PaymentFrequencyTypeNameField;
        
        private System.Nullable<bool> SecondDelinquentField;
        
        private System.Nullable<System.DateTime> SecondDelinquentDateField;
        
        private System.Nullable<System.DateTime> SecondDiscountDateField;
        
        private System.Nullable<bool> SecondDueField;
        
        private System.Nullable<System.DateTime> SecondDueDateField;
        
        private System.Nullable<bool> SecondEstimatedField;
        
        private System.Nullable<System.DateTime> SecondGoodThroughDateField;
        
        private System.Nullable<decimal> SecondInstallmentField;
        
        private System.Nullable<bool> SecondPaidField;
        
        private System.Nullable<System.DateTime> SecondPaidDateField;
        
        private System.Nullable<bool> SecondPartiallyPaidField;
        
        private System.Nullable<decimal> SecondPartiallyPaidAmountField;
        
        private System.Nullable<System.DateTime> SecondTaxesOutDateField;
        
        private string StateIDNumberField;
        
        private System.Nullable<int> TaxIDField;
        
        private string TaxIDNumberField;
        
        private string TaxIDNumberFurtherDescribedField;
        
        private System.Nullable<int> TaxTypeIDField;
        
        private string TaxTypeNameField;
        
        private string TaxingEntityField;
        
        private string TaxingEntityCityField;
        
        private string TaxingEntityPhoneField;
        
        private string TaxingEntityStateField;
        
        private string TaxingEntityStreet1Field;
        
        private string TaxingEntityStreet2Field;
        
        private string TaxingEntityZipCodeField;
        
        private System.Nullable<bool> ThirdDelinquentField;
        
        private System.Nullable<System.DateTime> ThirdDelinquentDateField;
        
        private System.Nullable<System.DateTime> ThirdDiscountDateField;
        
        private System.Nullable<bool> ThirdDueField;
        
        private System.Nullable<System.DateTime> ThirdDueDateField;
        
        private System.Nullable<bool> ThirdEstimatedField;
        
        private System.Nullable<System.DateTime> ThirdGoodThroughDateField;
        
        private System.Nullable<decimal> ThirdInstallmentField;
        
        private System.Nullable<bool> ThirdPaidField;
        
        private System.Nullable<System.DateTime> ThirdPaidDateField;
        
        private System.Nullable<bool> ThirdPartiallyPaidField;
        
        private System.Nullable<decimal> ThirdPartiallyPaidAmountField;
        
        private System.Nullable<System.DateTime> ThirdTaxesOutDateField;
        
        private System.Nullable<decimal> TotalAnnualTaxField;
        
        private System.Nullable<int> YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estimated
        {
            get
            {
                return this.EstimatedField;
            }
            set
            {
                this.EstimatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExemptionAdditional
        {
            get
            {
                return this.ExemptionAdditionalField;
            }
            set
            {
                this.ExemptionAdditionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExemptionHomeowners
        {
            get
            {
                return this.ExemptionHomeownersField;
            }
            set
            {
                this.ExemptionHomeownersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExemptionHomesteadSupplemental
        {
            get
            {
                return this.ExemptionHomesteadSupplementalField;
            }
            set
            {
                this.ExemptionHomesteadSupplementalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ExemptionMortgage
        {
            get
            {
                return this.ExemptionMortgageField;
            }
            set
            {
                this.ExemptionMortgageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FirstDelinquent
        {
            get
            {
                return this.FirstDelinquentField;
            }
            set
            {
                this.FirstDelinquentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FirstDelinquentDate
        {
            get
            {
                return this.FirstDelinquentDateField;
            }
            set
            {
                this.FirstDelinquentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FirstDiscountDate
        {
            get
            {
                return this.FirstDiscountDateField;
            }
            set
            {
                this.FirstDiscountDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FirstDue
        {
            get
            {
                return this.FirstDueField;
            }
            set
            {
                this.FirstDueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FirstDueDate
        {
            get
            {
                return this.FirstDueDateField;
            }
            set
            {
                this.FirstDueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FirstEstimated
        {
            get
            {
                return this.FirstEstimatedField;
            }
            set
            {
                this.FirstEstimatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FirstGoodThroughDate
        {
            get
            {
                return this.FirstGoodThroughDateField;
            }
            set
            {
                this.FirstGoodThroughDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FirstInstallment
        {
            get
            {
                return this.FirstInstallmentField;
            }
            set
            {
                this.FirstInstallmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FirstPaid
        {
            get
            {
                return this.FirstPaidField;
            }
            set
            {
                this.FirstPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FirstPaidDate
        {
            get
            {
                return this.FirstPaidDateField;
            }
            set
            {
                this.FirstPaidDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FirstPartiallyPaid
        {
            get
            {
                return this.FirstPartiallyPaidField;
            }
            set
            {
                this.FirstPartiallyPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FirstPartiallyPaidAmount
        {
            get
            {
                return this.FirstPartiallyPaidAmountField;
            }
            set
            {
                this.FirstPartiallyPaidAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FirstTaxesOutDate
        {
            get
            {
                return this.FirstTaxesOutDateField;
            }
            set
            {
                this.FirstTaxesOutDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FourthDelinquent
        {
            get
            {
                return this.FourthDelinquentField;
            }
            set
            {
                this.FourthDelinquentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FourthDelinquentDate
        {
            get
            {
                return this.FourthDelinquentDateField;
            }
            set
            {
                this.FourthDelinquentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FourthDiscountDate
        {
            get
            {
                return this.FourthDiscountDateField;
            }
            set
            {
                this.FourthDiscountDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FourthDue
        {
            get
            {
                return this.FourthDueField;
            }
            set
            {
                this.FourthDueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FourthDueDate
        {
            get
            {
                return this.FourthDueDateField;
            }
            set
            {
                this.FourthDueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FourthEstimated
        {
            get
            {
                return this.FourthEstimatedField;
            }
            set
            {
                this.FourthEstimatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FourthGoodThroughDate
        {
            get
            {
                return this.FourthGoodThroughDateField;
            }
            set
            {
                this.FourthGoodThroughDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FourthInstallment
        {
            get
            {
                return this.FourthInstallmentField;
            }
            set
            {
                this.FourthInstallmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FourthPaid
        {
            get
            {
                return this.FourthPaidField;
            }
            set
            {
                this.FourthPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FourthPaidDate
        {
            get
            {
                return this.FourthPaidDateField;
            }
            set
            {
                this.FourthPaidDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FourthPartiallyPaid
        {
            get
            {
                return this.FourthPartiallyPaidField;
            }
            set
            {
                this.FourthPartiallyPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FourthPartiallyPaidAmount
        {
            get
            {
                return this.FourthPartiallyPaidAmountField;
            }
            set
            {
                this.FourthPartiallyPaidAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FourthTaxesOutDate
        {
            get
            {
                return this.FourthTaxesOutDateField;
            }
            set
            {
                this.FourthTaxesOutDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Improvements
        {
            get
            {
                return this.ImprovementsField;
            }
            set
            {
                this.ImprovementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Land
        {
            get
            {
                return this.LandField;
            }
            set
            {
                this.LandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Other
        {
            get
            {
                return this.OtherField;
            }
            set
            {
                this.OtherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaymentFrequencyTypeID
        {
            get
            {
                return this.PaymentFrequencyTypeIDField;
            }
            set
            {
                this.PaymentFrequencyTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentFrequencyTypeName
        {
            get
            {
                return this.PaymentFrequencyTypeNameField;
            }
            set
            {
                this.PaymentFrequencyTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SecondDelinquent
        {
            get
            {
                return this.SecondDelinquentField;
            }
            set
            {
                this.SecondDelinquentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SecondDelinquentDate
        {
            get
            {
                return this.SecondDelinquentDateField;
            }
            set
            {
                this.SecondDelinquentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SecondDiscountDate
        {
            get
            {
                return this.SecondDiscountDateField;
            }
            set
            {
                this.SecondDiscountDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SecondDue
        {
            get
            {
                return this.SecondDueField;
            }
            set
            {
                this.SecondDueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SecondDueDate
        {
            get
            {
                return this.SecondDueDateField;
            }
            set
            {
                this.SecondDueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SecondEstimated
        {
            get
            {
                return this.SecondEstimatedField;
            }
            set
            {
                this.SecondEstimatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SecondGoodThroughDate
        {
            get
            {
                return this.SecondGoodThroughDateField;
            }
            set
            {
                this.SecondGoodThroughDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SecondInstallment
        {
            get
            {
                return this.SecondInstallmentField;
            }
            set
            {
                this.SecondInstallmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SecondPaid
        {
            get
            {
                return this.SecondPaidField;
            }
            set
            {
                this.SecondPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SecondPaidDate
        {
            get
            {
                return this.SecondPaidDateField;
            }
            set
            {
                this.SecondPaidDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SecondPartiallyPaid
        {
            get
            {
                return this.SecondPartiallyPaidField;
            }
            set
            {
                this.SecondPartiallyPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SecondPartiallyPaidAmount
        {
            get
            {
                return this.SecondPartiallyPaidAmountField;
            }
            set
            {
                this.SecondPartiallyPaidAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SecondTaxesOutDate
        {
            get
            {
                return this.SecondTaxesOutDateField;
            }
            set
            {
                this.SecondTaxesOutDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateIDNumber
        {
            get
            {
                return this.StateIDNumberField;
            }
            set
            {
                this.StateIDNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TaxID
        {
            get
            {
                return this.TaxIDField;
            }
            set
            {
                this.TaxIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxIDNumber
        {
            get
            {
                return this.TaxIDNumberField;
            }
            set
            {
                this.TaxIDNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxIDNumberFurtherDescribed
        {
            get
            {
                return this.TaxIDNumberFurtherDescribedField;
            }
            set
            {
                this.TaxIDNumberFurtherDescribedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TaxTypeID
        {
            get
            {
                return this.TaxTypeIDField;
            }
            set
            {
                this.TaxTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxTypeName
        {
            get
            {
                return this.TaxTypeNameField;
            }
            set
            {
                this.TaxTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxingEntity
        {
            get
            {
                return this.TaxingEntityField;
            }
            set
            {
                this.TaxingEntityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxingEntityCity
        {
            get
            {
                return this.TaxingEntityCityField;
            }
            set
            {
                this.TaxingEntityCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxingEntityPhone
        {
            get
            {
                return this.TaxingEntityPhoneField;
            }
            set
            {
                this.TaxingEntityPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxingEntityState
        {
            get
            {
                return this.TaxingEntityStateField;
            }
            set
            {
                this.TaxingEntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxingEntityStreet1
        {
            get
            {
                return this.TaxingEntityStreet1Field;
            }
            set
            {
                this.TaxingEntityStreet1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxingEntityStreet2
        {
            get
            {
                return this.TaxingEntityStreet2Field;
            }
            set
            {
                this.TaxingEntityStreet2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxingEntityZipCode
        {
            get
            {
                return this.TaxingEntityZipCodeField;
            }
            set
            {
                this.TaxingEntityZipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ThirdDelinquent
        {
            get
            {
                return this.ThirdDelinquentField;
            }
            set
            {
                this.ThirdDelinquentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThirdDelinquentDate
        {
            get
            {
                return this.ThirdDelinquentDateField;
            }
            set
            {
                this.ThirdDelinquentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThirdDiscountDate
        {
            get
            {
                return this.ThirdDiscountDateField;
            }
            set
            {
                this.ThirdDiscountDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ThirdDue
        {
            get
            {
                return this.ThirdDueField;
            }
            set
            {
                this.ThirdDueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThirdDueDate
        {
            get
            {
                return this.ThirdDueDateField;
            }
            set
            {
                this.ThirdDueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ThirdEstimated
        {
            get
            {
                return this.ThirdEstimatedField;
            }
            set
            {
                this.ThirdEstimatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThirdGoodThroughDate
        {
            get
            {
                return this.ThirdGoodThroughDateField;
            }
            set
            {
                this.ThirdGoodThroughDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ThirdInstallment
        {
            get
            {
                return this.ThirdInstallmentField;
            }
            set
            {
                this.ThirdInstallmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ThirdPaid
        {
            get
            {
                return this.ThirdPaidField;
            }
            set
            {
                this.ThirdPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThirdPaidDate
        {
            get
            {
                return this.ThirdPaidDateField;
            }
            set
            {
                this.ThirdPaidDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ThirdPartiallyPaid
        {
            get
            {
                return this.ThirdPartiallyPaidField;
            }
            set
            {
                this.ThirdPartiallyPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ThirdPartiallyPaidAmount
        {
            get
            {
                return this.ThirdPartiallyPaidAmountField;
            }
            set
            {
                this.ThirdPartiallyPaidAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ThirdTaxesOutDate
        {
            get
            {
                return this.ThirdTaxesOutDateField;
            }
            set
            {
                this.ThirdTaxesOutDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalAnnualTax
        {
            get
            {
                return this.TotalAnnualTaxField;
            }
            set
            {
                this.TotalAnnualTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataBookPage", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataBookPage : object
    {
        
        private string BookField;
        
        private int BookPageIDField;
        
        private int BookPageSourceTypeIDField;
        
        private string PageField;
        
        private int ReferenceIDField;
        
        private int SortOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookPageID
        {
            get
            {
                return this.BookPageIDField;
            }
            set
            {
                this.BookPageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookPageSourceTypeID
        {
            get
            {
                return this.BookPageSourceTypeIDField;
            }
            set
            {
                this.BookPageSourceTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferenceID
        {
            get
            {
                return this.ReferenceIDField;
            }
            set
            {
                this.ReferenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookPageDataRow", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class BookPageDataRow : SearchDataServiceNS.ReceiveSearchDataLienRequirementBase
    {
        
        private int BookPageIDField;
        
        private int BookPageSourceTypeIDField;
        
        private int ReferenceIDField;
        
        private int SortOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookPageID
        {
            get
            {
                return this.BookPageIDField;
            }
            set
            {
                this.BookPageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookPageSourceTypeID
        {
            get
            {
                return this.BookPageSourceTypeIDField;
            }
            set
            {
                this.BookPageSourceTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferenceID
        {
            get
            {
                return this.ReferenceIDField;
            }
            set
            {
                this.ReferenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataLienRequirementBase", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchDataServiceNS.ReceiveSearchDataLien))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchDataServiceNS.ReceiveSearchDataRequirement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchDataServiceNS.BookPageDataRow))]
    public partial class ReceiveSearchDataLienRequirementBase : object
    {
        
        private string AgainstField;
        
        private System.Nullable<decimal> AmountField;
        
        private string AssigneeField;
        
        private string AssigneeBookField;
        
        private string AssigneeInstrumentField;
        
        private string AssigneeLiberField;
        
        private string AssigneePageField;
        
        private string AssigneeVolumeField;
        
        private string AssignorField;
        
        private string BookField;
        
        private SearchDataServiceNS.ReceiveSearchDataBookPage[] BookPagesField;
        
        private string CaseNumberField;
        
        private string CountyField;
        
        private string CourtDistrictField;
        
        private string CourtTypeField;
        
        private System.Nullable<System.DateTime> DateField;
        
        private string DocumentNameField;
        
        private string EndorsementsField;
        
        private System.Nullable<bool> FlaggedField;
        
        private string GranteeField;
        
        private string GrantorField;
        
        private string HolderField;
        
        private string InFavorOfField;
        
        private System.Nullable<decimal> InstallmentAmountField;
        
        private string InstallmentNumberField;
        
        private string InstrumentField;
        
        private System.Nullable<bool> IsAllCapsField;
        
        private string LanguageField;
        
        private string LiberField;
        
        private System.Nullable<System.DateTime> MaturityDateField;
        
        private string PageField;
        
        private string PurposeField;
        
        private System.Nullable<System.DateTime> RecordedDateField;
        
        private string StateField;
        
        private string StateDistrictField;
        
        private string TaxYearsField;
        
        private string TrusteeField;
        
        private string VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Against
        {
            get
            {
                return this.AgainstField;
            }
            set
            {
                this.AgainstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assignee
        {
            get
            {
                return this.AssigneeField;
            }
            set
            {
                this.AssigneeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssigneeBook
        {
            get
            {
                return this.AssigneeBookField;
            }
            set
            {
                this.AssigneeBookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssigneeInstrument
        {
            get
            {
                return this.AssigneeInstrumentField;
            }
            set
            {
                this.AssigneeInstrumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssigneeLiber
        {
            get
            {
                return this.AssigneeLiberField;
            }
            set
            {
                this.AssigneeLiberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssigneePage
        {
            get
            {
                return this.AssigneePageField;
            }
            set
            {
                this.AssigneePageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssigneeVolume
        {
            get
            {
                return this.AssigneeVolumeField;
            }
            set
            {
                this.AssigneeVolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assignor
        {
            get
            {
                return this.AssignorField;
            }
            set
            {
                this.AssignorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataBookPage[] BookPages
        {
            get
            {
                return this.BookPagesField;
            }
            set
            {
                this.BookPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber
        {
            get
            {
                return this.CaseNumberField;
            }
            set
            {
                this.CaseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourtDistrict
        {
            get
            {
                return this.CourtDistrictField;
            }
            set
            {
                this.CourtDistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourtType
        {
            get
            {
                return this.CourtTypeField;
            }
            set
            {
                this.CourtTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this.DocumentNameField;
            }
            set
            {
                this.DocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endorsements
        {
            get
            {
                return this.EndorsementsField;
            }
            set
            {
                this.EndorsementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Flagged
        {
            get
            {
                return this.FlaggedField;
            }
            set
            {
                this.FlaggedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grantee
        {
            get
            {
                return this.GranteeField;
            }
            set
            {
                this.GranteeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grantor
        {
            get
            {
                return this.GrantorField;
            }
            set
            {
                this.GrantorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Holder
        {
            get
            {
                return this.HolderField;
            }
            set
            {
                this.HolderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InFavorOf
        {
            get
            {
                return this.InFavorOfField;
            }
            set
            {
                this.InFavorOfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InstallmentAmount
        {
            get
            {
                return this.InstallmentAmountField;
            }
            set
            {
                this.InstallmentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstallmentNumber
        {
            get
            {
                return this.InstallmentNumberField;
            }
            set
            {
                this.InstallmentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instrument
        {
            get
            {
                return this.InstrumentField;
            }
            set
            {
                this.InstrumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAllCaps
        {
            get
            {
                return this.IsAllCapsField;
            }
            set
            {
                this.IsAllCapsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Liber
        {
            get
            {
                return this.LiberField;
            }
            set
            {
                this.LiberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaturityDate
        {
            get
            {
                return this.MaturityDateField;
            }
            set
            {
                this.MaturityDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Purpose
        {
            get
            {
                return this.PurposeField;
            }
            set
            {
                this.PurposeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RecordedDate
        {
            get
            {
                return this.RecordedDateField;
            }
            set
            {
                this.RecordedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateDistrict
        {
            get
            {
                return this.StateDistrictField;
            }
            set
            {
                this.StateDistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxYears
        {
            get
            {
                return this.TaxYearsField;
            }
            set
            {
                this.TaxYearsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trustee
        {
            get
            {
                return this.TrusteeField;
            }
            set
            {
                this.TrusteeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataEasementRestrictionBase", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchDataServiceNS.ReceiveSearchDataRestriction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchDataServiceNS.ReceiveSearchDataEasement))]
    public partial class ReceiveSearchDataEasementRestrictionBase : object
    {
        
        private string BookField;
        
        private SearchDataServiceNS.ReceiveSearchDataBookPage[] BookPagesField;
        
        private System.Nullable<System.DateTime> DateField;
        
        private string DocumentNameField;
        
        private string GranteeField;
        
        private string GrantorField;
        
        private string InstrumentField;
        
        private System.Nullable<bool> IsAllCapsField;
        
        private string LanguageField;
        
        private string LiberField;
        
        private string PageField;
        
        private string PurposeField;
        
        private System.Nullable<System.DateTime> RecordedDateField;
        
        private string VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchDataServiceNS.ReceiveSearchDataBookPage[] BookPages
        {
            get
            {
                return this.BookPagesField;
            }
            set
            {
                this.BookPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this.DocumentNameField;
            }
            set
            {
                this.DocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grantee
        {
            get
            {
                return this.GranteeField;
            }
            set
            {
                this.GranteeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grantor
        {
            get
            {
                return this.GrantorField;
            }
            set
            {
                this.GrantorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instrument
        {
            get
            {
                return this.InstrumentField;
            }
            set
            {
                this.InstrumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAllCaps
        {
            get
            {
                return this.IsAllCapsField;
            }
            set
            {
                this.IsAllCapsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Liber
        {
            get
            {
                return this.LiberField;
            }
            set
            {
                this.LiberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Purpose
        {
            get
            {
                return this.PurposeField;
            }
            set
            {
                this.PurposeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RecordedDate
        {
            get
            {
                return this.RecordedDateField;
            }
            set
            {
                this.RecordedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataResponse", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSearchDataResponse : object
    {
        
        private string MessageField;
        
        private SearchDataServiceNS.ReceiveSearchDataResponseCode ResponseCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SearchDataServiceNS.ReceiveSearchDataResponseCode ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSearchDataResponseCode", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public enum ReceiveSearchDataResponseCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_LOGIN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_FILE_NUMBER = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOWN_FOR_MAINTENANCE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNEXPECTED_ERROR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEARCH_DATA_ERROR = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LIEN_ERROR = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUIREMENT_ERROR = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EASEMENT_ERROR = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESTRICTION_ERROR = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHAIN_OF_TITLE_ERROR = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TAX_ERROR = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchDataServiceNS.IReceiveSearchDataService")]
    public interface IReceiveSearchDataService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSearchDataService/ReceiveSearchData", ReplyAction="http://tempuri.org/IReceiveSearchDataService/ReceiveSearchDataResponse")]
        System.Threading.Tasks.Task<SearchDataServiceNS.ReceiveSearchDataResponse> ReceiveSearchDataAsync(SearchDataServiceNS.ReceiveSearchDataData SearchData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IReceiveSearchDataServiceChannel : SearchDataServiceNS.IReceiveSearchDataService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ReceiveSearchDataServiceClient : System.ServiceModel.ClientBase<SearchDataServiceNS.IReceiveSearchDataService>, SearchDataServiceNS.IReceiveSearchDataService
    {
        
        public ReceiveSearchDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SearchDataServiceNS.ReceiveSearchDataResponse> ReceiveSearchDataAsync(SearchDataServiceNS.ReceiveSearchDataData SearchData)
        {
            return base.Channel.ReceiveSearchDataAsync(SearchData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
