//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderPlacementServiceNS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.Address", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OrderPlacementServiceNS.OrderPlacementServicePropertyAddress))]
    public partial class OrderPlacementServiceAddress : object
    {
        
        private string AddressStreetInfoField;
        
        private string CityField;
        
        private string DescriptionField;
        
        private string LegalDescriptionField;
        
        private string ParcelIDField;
        
        private string ParcelID2Field;
        
        private string ParcelID3Field;
        
        private string ParcelID4Field;
        
        private OrderPlacementServiceNS.PlattedProperty[] PlattedField;
        
        private string StateField;
        
        private string StreetDirectionField;
        
        private string StreetNameField;
        
        private string StreetNumberField;
        
        private string StreetSuffixField;
        
        private string UnitField;
        
        private OrderPlacementServiceNS.UnplattedProperty[] UnplattedField;
        
        private string ZipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressStreetInfo
        {
            get
            {
                return this.AddressStreetInfoField;
            }
            set
            {
                this.AddressStreetInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalDescription
        {
            get
            {
                return this.LegalDescriptionField;
            }
            set
            {
                this.LegalDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelID
        {
            get
            {
                return this.ParcelIDField;
            }
            set
            {
                this.ParcelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelID2
        {
            get
            {
                return this.ParcelID2Field;
            }
            set
            {
                this.ParcelID2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelID3
        {
            get
            {
                return this.ParcelID3Field;
            }
            set
            {
                this.ParcelID3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelID4
        {
            get
            {
                return this.ParcelID4Field;
            }
            set
            {
                this.ParcelID4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderPlacementServiceNS.PlattedProperty[] Platted
        {
            get
            {
                return this.PlattedField;
            }
            set
            {
                this.PlattedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetDirection
        {
            get
            {
                return this.StreetDirectionField;
            }
            set
            {
                this.StreetDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNumber
        {
            get
            {
                return this.StreetNumberField;
            }
            set
            {
                this.StreetNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetSuffix
        {
            get
            {
                return this.StreetSuffixField;
            }
            set
            {
                this.StreetSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderPlacementServiceNS.UnplattedProperty[] Unplatted
        {
            get
            {
                return this.UnplattedField;
            }
            set
            {
                this.UnplattedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.PropertyAddress", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class OrderPlacementServicePropertyAddress : OrderPlacementServiceNS.OrderPlacementServiceAddress
    {
        
        private string CountyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlattedProperty", Namespace="")]
    public partial class PlattedProperty : object
    {
        
        private string BookField;
        
        private System.Nullable<int> BookPageSourceTypeIDField;
        
        private OrderPlacementServiceNS.LotBlockOther[] LotBlockOtherField;
        
        private string PageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> BookPageSourceTypeID
        {
            get
            {
                return this.BookPageSourceTypeIDField;
            }
            set
            {
                this.BookPageSourceTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public OrderPlacementServiceNS.LotBlockOther[] LotBlockOther
        {
            get
            {
                return this.LotBlockOtherField;
            }
            set
            {
                this.LotBlockOtherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnplattedProperty", Namespace="")]
    public partial class UnplattedProperty : object
    {
        
        private string CodeField;
        
        private string RangeField;
        
        private string RangeDirectionField;
        
        private string SectionField;
        
        private string TownshipField;
        
        private string TownshipDirectionField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Range
        {
            get
            {
                return this.RangeField;
            }
            set
            {
                this.RangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RangeDirection
        {
            get
            {
                return this.RangeDirectionField;
            }
            set
            {
                this.RangeDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Section
        {
            get
            {
                return this.SectionField;
            }
            set
            {
                this.SectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Township
        {
            get
            {
                return this.TownshipField;
            }
            set
            {
                this.TownshipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TownshipDirection
        {
            get
            {
                return this.TownshipDirectionField;
            }
            set
            {
                this.TownshipDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LotBlockOther", Namespace="")]
    public partial class LotBlockOther : object
    {
        
        private string BlockField;
        
        private string LotField;
        
        private string OtherField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Block
        {
            get
            {
                return this.BlockField;
            }
            set
            {
                this.BlockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Lot
        {
            get
            {
                return this.LotField;
            }
            set
            {
                this.LotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Other
        {
            get
            {
                return this.OtherField;
            }
            set
            {
                this.OtherField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.Partner", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class OrderPlacementServicePartner : object
    {
        
        private OrderPlacementServiceNS.OrderPlacementServiceAddress AddressField;
        
        private string ContactNameField;
        
        private string NameField;
        
        private int PartnerTypeIDField;
        
        private string PhoneField;
        
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderPlacementServiceNS.OrderPlacementServiceAddress Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartnerTypeID
        {
            get
            {
                return this.PartnerTypeIDField;
            }
            set
            {
                this.PartnerTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.BuyerSeller", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class OrderPlacementServiceBuyerSeller : object
    {
        
        private OrderPlacementServiceNS.OrderPlacementServiceAddress AddressField;
        
        private string EmailField;
        
        private string EntityNameField;
        
        private int EntityTypeIDField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string MaritalStatusField;
        
        private string MiddleNameField;
        
        private string PhoneField;
        
        private string PrefixField;
        
        private string SSNField;
        
        private OrderPlacementServiceNS.OrderPlacementServiceBuyerSeller SpouseField;
        
        private string SuffixField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderPlacementServiceNS.OrderPlacementServiceAddress Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityName
        {
            get
            {
                return this.EntityNameField;
            }
            set
            {
                this.EntityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntityTypeID
        {
            get
            {
                return this.EntityTypeIDField;
            }
            set
            {
                this.EntityTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus
        {
            get
            {
                return this.MaritalStatusField;
            }
            set
            {
                this.MaritalStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix
        {
            get
            {
                return this.PrefixField;
            }
            set
            {
                this.PrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN
        {
            get
            {
                return this.SSNField;
            }
            set
            {
                this.SSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderPlacementServiceNS.OrderPlacementServiceBuyerSeller Spouse
        {
            get
            {
                return this.SpouseField;
            }
            set
            {
                this.SpouseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix
        {
            get
            {
                return this.SuffixField;
            }
            set
            {
                this.SuffixField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.PriorPolicy", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class OrderPlacementServicePriorPolicy : object
    {
        
        private decimal ConsiderationField;
        
        private System.DateTime PolicyDateField;
        
        private decimal PremiumField;
        
        private decimal SalesPriceOrLoanAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Consideration
        {
            get
            {
                return this.ConsiderationField;
            }
            set
            {
                this.ConsiderationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyDate
        {
            get
            {
                return this.PolicyDateField;
            }
            set
            {
                this.PolicyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Premium
        {
            get
            {
                return this.PremiumField;
            }
            set
            {
                this.PremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesPriceOrLoanAmount
        {
            get
            {
                return this.SalesPriceOrLoanAmountField;
            }
            set
            {
                this.SalesPriceOrLoanAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.BuyerPayoff", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class OrderPlacementServiceBuyerPayoff : object
    {
        
        private decimal InterestField;
        
        private System.Nullable<System.DateTime> OriginationField;
        
        private decimal PrincipalBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Interest
        {
            get
            {
                return this.InterestField;
            }
            set
            {
                this.InterestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Origination
        {
            get
            {
                return this.OriginationField;
            }
            set
            {
                this.OriginationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrincipalBalance
        {
            get
            {
                return this.PrincipalBalanceField;
            }
            set
            {
                this.PrincipalBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.SellerPayoff", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class OrderPlacementServiceSellerPayoff : object
    {
        
        private decimal InterestField;
        
        private System.Nullable<System.DateTime> OriginationField;
        
        private decimal PrincipalBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Interest
        {
            get
            {
                return this.InterestField;
            }
            set
            {
                this.InterestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Origination
        {
            get
            {
                return this.OriginationField;
            }
            set
            {
                this.OriginationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrincipalBalance
        {
            get
            {
                return this.PrincipalBalanceField;
            }
            set
            {
                this.PrincipalBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class PlaceOrderResponse : object
    {
        
        private string AQUADecisionField;
        
        private int ResWareFileIDField;
        
        private string ResWareFileNumberField;
        
        private string ResponseField;
        
        private int ResponseCodeField;
        
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQUADecision
        {
            get
            {
                return this.AQUADecisionField;
            }
            set
            {
                this.AQUADecisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResWareFileID
        {
            get
            {
                return this.ResWareFileIDField;
            }
            set
            {
                this.ResWareFileIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResWareFileNumber
        {
            get
            {
                return this.ResWareFileNumberField;
            }
            set
            {
                this.ResWareFileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Response
        {
            get
            {
                return this.ResponseField;
            }
            set
            {
                this.ResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderPlacementServiceNS.IOrderPlacementService")]
    public interface IOrderPlacementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/PlaceOrder", ReplyAction="http://tempuri.org/IOrderPlacementService/PlaceOrderResponse")]
        System.Threading.Tasks.Task<OrderPlacementServiceNS.PlaceOrderResponse> PlaceOrderAsync(
                    int ClientID, 
                    int OfficeID, 
                    string FileNumber, 
                    OrderPlacementServiceNS.OrderPlacementServicePropertyAddress PropertyAddress, 
                    int ClientsClientID, 
                    int TransactionTypeID, 
                    int ProductID, 
                    int UnderwriterID, 
                    int PrimaryContactID, 
                    System.Nullable<System.DateTime> EstimatedSettlementDate, 
                    decimal SalesPrice, 
                    decimal LoanAmount, 
                    string LoanNumber, 
                    decimal CashOut, 
                    string[] PayoffMortgagees, 
                    int[] OptionalActionGroupIDs, 
                    OrderPlacementServiceNS.OrderPlacementServicePartner Lender, 
                    bool IsLender, 
                    OrderPlacementServiceNS.OrderPlacementServiceBuyerSeller[] Buyers, 
                    OrderPlacementServiceNS.OrderPlacementServiceBuyerSeller[] Sellers, 
                    OrderPlacementServiceNS.OrderPlacementServicePartner[] AdditionalPartners, 
                    OrderPlacementServiceNS.OrderPlacementServicePartner ClientsClient, 
                    string Notes, 
                    bool RequestAQUADecision, 
                    System.Nullable<decimal> OriginalDebtAmount, 
                    bool IsWholesaleOrder, 
                    string CPLCompany, 
                    string CPLDivision, 
                    string CPLStreet1, 
                    string CPLStreet2, 
                    string CPLCity, 
                    string CPLState, 
                    string CPLZip, 
                    string AssetNumber, 
                    OrderPlacementServiceNS.OrderPlacementServicePriorPolicy PriorLenderPolicy, 
                    OrderPlacementServiceNS.OrderPlacementServicePriorPolicy PriorOwnerPolicy, 
                    OrderPlacementServiceNS.OrderPlacementServiceBuyerPayoff[] BuyerPayoffs, 
                    OrderPlacementServiceNS.OrderPlacementServiceSellerPayoff[] SellerPayoffs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IOrderPlacementServiceChannel : OrderPlacementServiceNS.IOrderPlacementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class OrderPlacementServiceClient : System.ServiceModel.ClientBase<OrderPlacementServiceNS.IOrderPlacementService>, OrderPlacementServiceNS.IOrderPlacementService
    {
        
        public OrderPlacementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OrderPlacementServiceNS.PlaceOrderResponse> PlaceOrderAsync(
                    int ClientID, 
                    int OfficeID, 
                    string FileNumber, 
                    OrderPlacementServiceNS.OrderPlacementServicePropertyAddress PropertyAddress, 
                    int ClientsClientID, 
                    int TransactionTypeID, 
                    int ProductID, 
                    int UnderwriterID, 
                    int PrimaryContactID, 
                    System.Nullable<System.DateTime> EstimatedSettlementDate, 
                    decimal SalesPrice, 
                    decimal LoanAmount, 
                    string LoanNumber, 
                    decimal CashOut, 
                    string[] PayoffMortgagees, 
                    int[] OptionalActionGroupIDs, 
                    OrderPlacementServiceNS.OrderPlacementServicePartner Lender, 
                    bool IsLender, 
                    OrderPlacementServiceNS.OrderPlacementServiceBuyerSeller[] Buyers, 
                    OrderPlacementServiceNS.OrderPlacementServiceBuyerSeller[] Sellers, 
                    OrderPlacementServiceNS.OrderPlacementServicePartner[] AdditionalPartners, 
                    OrderPlacementServiceNS.OrderPlacementServicePartner ClientsClient, 
                    string Notes, 
                    bool RequestAQUADecision, 
                    System.Nullable<decimal> OriginalDebtAmount, 
                    bool IsWholesaleOrder, 
                    string CPLCompany, 
                    string CPLDivision, 
                    string CPLStreet1, 
                    string CPLStreet2, 
                    string CPLCity, 
                    string CPLState, 
                    string CPLZip, 
                    string AssetNumber, 
                    OrderPlacementServiceNS.OrderPlacementServicePriorPolicy PriorLenderPolicy, 
                    OrderPlacementServiceNS.OrderPlacementServicePriorPolicy PriorOwnerPolicy, 
                    OrderPlacementServiceNS.OrderPlacementServiceBuyerPayoff[] BuyerPayoffs, 
                    OrderPlacementServiceNS.OrderPlacementServiceSellerPayoff[] SellerPayoffs)
        {
            return base.Channel.PlaceOrderAsync(ClientID, OfficeID, FileNumber, PropertyAddress, ClientsClientID, TransactionTypeID, ProductID, UnderwriterID, PrimaryContactID, EstimatedSettlementDate, SalesPrice, LoanAmount, LoanNumber, CashOut, PayoffMortgagees, OptionalActionGroupIDs, Lender, IsLender, Buyers, Sellers, AdditionalPartners, ClientsClient, Notes, RequestAQUADecision, OriginalDebtAmount, IsWholesaleOrder, CPLCompany, CPLDivision, CPLStreet1, CPLStreet2, CPLCity, CPLState, CPLZip, AssetNumber, PriorLenderPolicy, PriorOwnerPolicy, BuyerPayoffs, SellerPayoffs);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
