// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReswareConnectorWeb.Data;

#nullable disable

namespace ReswareConnectorWeb.Data.Migrations
{
    [DbContext(typeof(ReswareConnectorDbContext))]
    [Migration("20251201180208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReswareConnectorWeb.Data.Entities.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("data_path");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_number");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("processed");

                    b.Property<DateTime>("ReceivedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received_time");

                    b.Property<byte>("TransactionTypeId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("transaction_type_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("FileNumber")
                        .HasDatabaseName("idx_transactions_file_number");

                    b.HasIndex("Processed")
                        .HasDatabaseName("idx_transactions_processed");

                    b.HasIndex("ReceivedTime")
                        .HasDatabaseName("idx_transactions_received_time");

                    b.HasIndex("TransactionTypeId")
                        .HasDatabaseName("idx_transactions_type_id");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("ReswareConnectorWeb.Data.Entities.TransactionItem", b =>
                {
                    b.Property<long>("TransactionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TransactionItemId"));

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated_time");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("processed");

                    b.Property<ulong?>("ResponseSent")
                        .HasColumnType("BIT(1)")
                        .HasColumnName("response_sent");

                    b.Property<byte?>("RetryCount")
                        .HasColumnType("TINYINT UNSIGNED")
                        .HasColumnName("retry_count");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    b.Property<byte>("TransactionTypeId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("transaction_type_id");

                    b.HasKey("TransactionItemId");

                    b.HasIndex("Processed")
                        .HasDatabaseName("idx_transaction_items_processed");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("idx_transaction_items_transaction_id");

                    b.HasIndex("TransactionTypeId")
                        .HasDatabaseName("idx_transaction_items_type_id");

                    b.HasIndex("TransactionId", "Processed")
                        .HasDatabaseName("idx_transaction_items_transaction_processed");

                    b.ToTable("TransactionItems", (string)null);
                });

            modelBuilder.Entity("ReswareConnectorWeb.Data.Entities.TransactionResponse", b =>
                {
                    b.Property<long>("TransactionResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_response_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TransactionResponseId"));

                    b.Property<DateTime>("ReceivedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received_time");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("int")
                        .HasColumnName("response_code");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("response_message");

                    b.Property<long>("TransactionItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_item_id");

                    b.HasKey("TransactionResponseId");

                    b.HasIndex("ReceivedTime")
                        .HasDatabaseName("idx_transaction_responses_received_time");

                    b.HasIndex("ResponseCode")
                        .HasDatabaseName("idx_transaction_responses_code");

                    b.HasIndex("TransactionItemId")
                        .HasDatabaseName("idx_transaction_responses_item_id");

                    b.ToTable("TransactionResponses", (string)null);
                });

            modelBuilder.Entity("ReswareConnectorWeb.Data.Entities.TransactionItem", b =>
                {
                    b.HasOne("ReswareConnectorWeb.Data.Entities.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ReswareConnectorWeb.Data.Entities.TransactionResponse", b =>
                {
                    b.HasOne("ReswareConnectorWeb.Data.Entities.TransactionItem", "TransactionItem")
                        .WithMany("Responses")
                        .HasForeignKey("TransactionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionItem");
                });

            modelBuilder.Entity("ReswareConnectorWeb.Data.Entities.Transaction", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReswareConnectorWeb.Data.Entities.TransactionItem", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
