//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionEventServiceNS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveActionEventData", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveActionEventData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ActionEventCodeField;
        
        private string FileNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionEventCode
        {
            get
            {
                return this.ActionEventCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ActionEventCodeField, value) != true))
                {
                    this.ActionEventCodeField = value;
                    this.RaisePropertyChanged("ActionEventCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FileNumber
        {
            get
            {
                return this.FileNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FileNumberField, value) != true))
                {
                    this.FileNumberField = value;
                    this.RaisePropertyChanged("FileNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveActionEventResponse", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveActionEventResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string MessageField;
        
        private ActionEventServiceNS.ReceiveActionEventResponseCode ResponseCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ActionEventServiceNS.ReceiveActionEventResponseCode ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                if ((this.ResponseCodeField.Equals(value) != true))
                {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveActionEventResponseCode", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public enum ReceiveActionEventResponseCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_LOGIN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_FILE_NUMBER = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOWN_FOR_MAINTENANCE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNEXPECTED_ERROR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTION_EVENT_NOT_FOUND = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActionEventServiceNS.IReceiveActionEventService")]
    public interface IReceiveActionEventService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveActionEventService/ReceiveActionEvent", ReplyAction="http://tempuri.org/IReceiveActionEventService/ReceiveActionEventResponse")]
        System.Threading.Tasks.Task<ActionEventServiceNS.ReceiveActionEventResponse> ReceiveActionEventAsync(ActionEventServiceNS.ReceiveActionEventData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IReceiveActionEventServiceChannel : ActionEventServiceNS.IReceiveActionEventService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ReceiveActionEventServiceClient : System.ServiceModel.ClientBase<ActionEventServiceNS.IReceiveActionEventService>, ActionEventServiceNS.IReceiveActionEventService
    {
        
        public ReceiveActionEventServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ActionEventServiceNS.ReceiveActionEventResponse> ReceiveActionEventAsync(ActionEventServiceNS.ReceiveActionEventData data)
        {
            return base.Channel.ReceiveActionEventAsync(data);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
